module.exports = [
  {
    id: 1,
    film_id: 3,
    result: "WINNER",
    category: "Best History Documentary",
    awardshow: "Royal Television Society Programme Awards",
    link: "https://rts.org.uk/award/rts-programme-awards-2021",
  },
  {
    id: 2,
    film_id: 3,
    result: "WINNER",
    category: "Debut Presenter Award",
    awardshow: "Edinburgh TV Festival's New Voice Awards",
    link: "https://www.thetvfestival.com/talent-schemes/newvoiceawards/nva-individual-awards-2021/",
  },
  {
    id: 3,
    film_id: 3,
    result: "WINNER",
    category: "Best Presenter",
    awardshow: "Grierson Awards",
    link: "https://griersontrust.org/grierson-awards/the-grierson-awards/nominations/",
  },
  {
    id: 4,
    film_id: 3,
    result: "NOMINEE",
    category: "Best Documentary",
    awardshow: "Edinburgh TV Awards",
    link: "https://www.thetvfestival.com/whats-on/edinburgh-tv-awards-2021/",
  },
  {
    id: 5,
    film_id: 3,
    result: "NOMINEE",
    category: "Best Presenter",
    awardshow: "Royal Television Society Programme Awards",
    link: "https://rts.org.uk/award/rts-programme-awards-2021",
  },
  {
    id: 6,
    film_id: 3,
    result: "NOMINEE",
    category: "Best History Documentary",
    awardshow: "Grierson Awards",
    link: "https://griersontrust.org/grierson-awards/the-grierson-awards/nominations/",
  },
  {
    id: 7,
    film_id: 3,
    result: "HIGHLY COMMENDED",
    category: "Best Documentary",
    awardshow: "Broadcast Awards",
    link: "https://broadcastawards.co.uk/winners",
  },
  {
    id: 8,
    film_id: 4,
    result: "WINNER",
    category: "Debut Director Award",
    awardshow: "Edinburgh TV Festival's New Voice Awards",
    link: "https://www.thetvfestival.com/talent-schemes/newvoiceawards/nva-individual-awards-2021/",
  },
  {
    id: 9,
    film_id: 6,
    result: "WINNER",
    category: "Best Presenter",
    awardshow: "Royal Television Society Programme Awards",
    link: "https://rts.org.uk/award/rts-programme-awards-2020-partnership-audio-network",
  },
  {
    id: 10,
    film_id: 6,
    result: "WINNER",
    category: "Best Presenter",
    awardshow: "Grierson Documentary Awards",
    link: "https://griersontrust.org/assets/files/awards/programmes/Grierson-2020-the-British-Documentary-Awards-programme.pdf",
  },
  {
    id: 11,
    film_id: 6,
    result: "NOMINEE",
    category: "Best Documentary Series",
    awardshow: "Royal Television Society Programme Awards",
    link: "https://rts.org.uk/award/rts-programme-awards-2020-partnership-audio-network",
  },
  {
    id: 12,
    film_id: 6,
    result: "NOMINEE",
    category: "Best Documentary Series",
    awardshow: "Grierson Documentary Awards",
    link: "https://griersontrust.org/assets/files/awards/programmes/Grierson-2020-the-British-Documentary-Awards-programme.pdf",
  },
  {
    id: 13,
    film_id: 7,
    result: "NOMINATION FOR Chanté JOSEPH",
    category: "Debut Presenter Award",
    awardshow: "Edinburgh TV Festival's New Voice Awards",
    link: "https://mailchi.mp/thetvfestival.com/new-voice-awards-shortlist-revealed-482550",
  },
];
